[[pages]]
path =  "DL_SCAN.py"
name =  "ğŸ”¬_Preprocessing_and_Segmentation"

[[pages]]
path =  "pages/01_ğŸ“‰_Single-cell_Analysis.py"

[[pages]]
path =  "pages/02_ğŸ“ˆğŸ“‰_Multi-cell_Analysis.py"

[[pages]]
path =  "pages/03_ğŸ“_Read_Me.py"